# Nome do seu projeto
name = "zap-gpt-fotikos"

# Versão do serviço
version = 1

# Definição dos serviços
[[services]]
  # Serviço web
  name = "web"
  # Use a imagem Docker localizada no diretório atual (.)
  image = "."
  # Quantidade de instâncias a serem iniciadas
  scale = 1
  # Porta que sua aplicação está ouvindo
  port = 3000
  # Comando para iniciar o aplicativo
  command = "npm start"
