[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
startCommand = "npm start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[commands]]
name = "Install Dependencies"
command = "sh install-dependencies.sh"
